   repos:
     - repo: https://github.com/pre-commit/pre-commit-hooks
       rev: v4.0.1
       hooks:
         - id: trailing-whitespace
         - id: end-of-file-fixer
         - id: check-yaml
         - id: check-added-large-files
     - repo: https://github.com/pocc/pre-commit-hooks
       rev: v1.3.5
       hooks:
         - id: clang-format
           args: [-i]
           files: \.(cpp|hpp)$
           exclude: /_deps/
