set(CMAKE_CXX_STANDARD 11)
set(CMAKE_CXX_STANDARD_REQUIRED ON)
set(CMAKE_CXX_EXTENSIONS OFF)

file(GLOB_RECURSE ALL_EXAMPLE_SOURCES "${CMAKE_SOURCE_DIR}/examples/*.cpp")

add_executable(ZipViewExamples ${ALL_EXAMPLE_SOURCES})

target_compile_options(ZipViewExamples PRIVATE ${PROJECT_COMPILE_OPTIONS})
